name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline the solution and alternatives considered
  - type: input
    id: scope
    attributes:
      label: Scope
      description: Rough scope/complexity (S/M/L)
