name: ci

on:
  push:
    branches: [ "main", "beta", "feature/**" ]
  pull_request:
    branches: [ "main", "beta" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        run: npm test --if-present
      - name: Build
        run: npm run build --if-present
      - name: Version & Hygiene Checks
        run: |
          set -euo pipefail
          VER=$(jq -r .version package.json)
          echo "Expected version: $VER"
          grep -q "${VER}" public/index.html || (echo "Version mismatch in public/index.html" && exit 1)
          grep -q "${VER}" CHANGELOG.md || (echo "Version missing in CHANGELOG.md" && exit 1)
          ! rg -n "(console\.log\(|debugger;|TODO|FIXME)" || (echo "Found debug/TODO markers" && exit 1)